language: node_js
node_js:
  # - "0.11"
  - "0.10"
before_install: 
  - npm install -g grunt-cli
  - sudo apt-get update -qq && sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

install: npm install
before_script: grunt build
